### ISSUE TITLE
platform(req): Acast

### ISSUE THREAD

**Issue by LProgead** [punctuations/presence#16]
**What is the platform?**
[Acast](https://www.acast.com/)

**What specific features would you like to see with this presence?**
- Podcast title
- Podcast author
- Podcast icon
- Podcast description
- Podcast tags (maybe let the user decide if he wants the tags)
- *If possible*, number of episodes

**Comment by punctuations** [comment]
I'll take a peek into its api and see if its possible!

**Comment by punctuations** [comment]
So sorry about the lack of information, for the past little bit I've been dealing with some stuff, I'll make sure I get around to this soon!

**Comment by punctuations** [comment]
So sorry for how long this took, but unfortunately the API is limited to "60 requests/minute", which is too low to be viable, thank you so much for taking the time to make a request in the first place!
