### ISSUE TITLE
bug(Twitter): Long Tweets aren't showed entirely

### ISSUE THREAD

**Issue by LProgead** [punctuations/presence#17]
**Describe the bug**
Long Tweets aren't showed entirely

**To Reproduce**

1. Ask a presence of a Tweet longer than 252 characters

**Expected behavior**
The Tweet is showed entirely.

**Current behavior**
Only the first 252 characters are showed.

**Screenshots**
![image](https://user-images.githubusercontent.com/43679817/127780224-37dc054e-5884-4868-8e84-af3983d19416.png)

**Desktop:**

- OS: Linux
- Browser: Brave
- Version: Version 1.28.88 Chromium: 92.0.4515.107 (Official build) beta (64 bits)

**Comment by punctuations** [comment]
Thank you for the concern about this but unfortunately it has to be like this else the text would go off the image, I added the cap of 252 characters to prevent this; however, I would love to find a better way to execute this but as of now I can't really think of a better way, if you can let me know and I'll try it out!
